# Generated by Django 6.0.6 on 2026-07-11 19:27

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Amenity",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100, unique=True)),
                ("icon", models.CharField(blank=True, max_length=100)),
            ],
            options={
                "verbose_name_plural": "Amenities",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="Venue",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("slug", models.SlugField(blank=True, unique=True)),
                ("short_description", models.CharField(blank=True, max_length=200)),
                ("description", models.TextField()),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("wedding_hall", "Wedding Hall"),
                            ("banquet_hall", "Banquet Hall"),
                            ("conference_hall", "Conference Hall"),
                            ("auditorium", "Auditorium"),
                            ("hotel", "Hotel"),
                            ("resort", "Resort"),
                            ("party_hall", "Party Hall"),
                            ("meeting_room", "Meeting Room"),
                            ("farmhouse", "Farm House"),
                            ("villa", "Villa"),
                            ("beachside", "Beachside Venue"),
                        ],
                        max_length=30,
                    ),
                ),
                (
                    "price_per_hour",
                    models.DecimalField(decimal_places=2, max_digits=10),
                ),
                (
                    "cleaning_fee",
                    models.DecimalField(decimal_places=2, default=0, max_digits=10),
                ),
                (
                    "service_fee",
                    models.DecimalField(decimal_places=2, default=0, max_digits=10),
                ),
                ("capacity", models.PositiveIntegerField()),
                ("address", models.TextField()),
                ("city", models.CharField(max_length=100)),
                ("state", models.CharField(max_length=100)),
                ("landmark", models.CharField(blank=True, max_length=255)),
                ("contact_phone", models.CharField(max_length=15)),
                ("contact_email", models.EmailField(blank=True, max_length=254)),
                ("opening_time", models.TimeField()),
                ("closing_time", models.TimeField()),
                ("minimum_booking_hours", models.PositiveIntegerField(default=1)),
                ("parking_capacity", models.PositiveIntegerField(default=0)),
                ("is_available", models.BooleanField(default=True)),
                ("is_featured", models.BooleanField(default=False)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("approved", "Approved"),
                            ("rejected", "Rejected"),
                        ],
                        default="pending",
                        max_length=20,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "amenities",
                    models.ManyToManyField(
                        blank=True, related_name="venues", to="venues.amenity"
                    ),
                ),
                (
                    "owner",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="venues",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="VenueImage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("image", models.ImageField(upload_to="venue_images/")),
                ("caption", models.CharField(blank=True, max_length=255)),
                ("is_primary", models.BooleanField(default=False)),
                ("uploaded_at", models.DateTimeField(auto_now_add=True)),
                (
                    "venue",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="images",
                        to="venues.venue",
                    ),
                ),
            ],
            options={
                "ordering": ["id"],
            },
        ),
        migrations.CreateModel(
            name="VenueCapacity",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "layout",
                    models.CharField(
                        choices=[
                            ("standing", "Standing"),
                            ("banquet", "Banquet"),
                            ("conference", "Conference"),
                            ("theater", "Theater"),
                            ("classroom", "Classroom"),
                            ("u_shape", "U Shape"),
                            ("boardroom", "Board Room"),
                        ],
                        max_length=20,
                    ),
                ),
                ("capacity", models.PositiveIntegerField()),
                (
                    "venue",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="layouts",
                        to="venues.venue",
                    ),
                ),
            ],
            options={
                "ordering": ["layout"],
                "unique_together": {("venue", "layout")},
            },
        ),
    ]
