# Generated by Django 6.0.6 on 2026-07-23 20:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("venues", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="venueimage",
            name="caption",
        ),
        migrations.AlterField(
            model_name="venue",
            name="cleaning_fee",
            field=models.DecimalField(
                blank=True, decimal_places=2, default=0, max_digits=10
            ),
        ),
        migrations.AlterField(
            model_name="venue",
            name="contact_phone",
            field=models.CharField(blank=True, max_length=15),
        ),
        migrations.AlterField(
            model_name="venue",
            name="service_fee",
            field=models.DecimalField(
                blank=True, decimal_places=2, default=0, max_digits=10
            ),
        ),
    ]
