# Generated by Django 6.0.6 on 2026-07-24 18:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("venues", "0002_remove_venueimage_caption_alter_venue_cleaning_fee_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="venue",
            old_name="address",
            new_name="location",
        ),
        migrations.RemoveField(
            model_name="venue",
            name="cleaning_fee",
        ),
        migrations.RemoveField(
            model_name="venue",
            name="landmark",
        ),
        migrations.RemoveField(
            model_name="venue",
            name="service_fee",
        ),
        migrations.RemoveField(
            model_name="venue",
            name="short_description",
        ),
        migrations.RemoveField(
            model_name="venue",
            name="state",
        ),
        migrations.AddField(
            model_name="venue",
            name="Pincode",
            field=models.CharField(default=678512, max_length=10),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="venue",
            name="category",
            field=models.CharField(
                choices=[
                    ("wedding_hall", "Wedding Hall"),
                    ("banquet_hall", "Banquet Hall"),
                    ("auditorium", "Auditorium"),
                    ("cafe", "Cafe"),
                    ("resort", "Resort"),
                    ("meeting_room", "Meeting Room"),
                    ("beachside", "Beachside Venue"),
                ],
                max_length=30,
            ),
        ),
    ]
